# 플러그인 언어 설정
lang: "ko"

# 월드 가드 필요
# 구매를 시도하는 청크에 해당 구역이 존재할 경우 구매 불가
cant-bought-region:
  - spawn1

# 구매 불가 월드
cant-bought:
  - spawn

# 월드별 구매 가능 최대 개수
bought-limit:
  default: 10
  world: 99
  world_nether: 4
  world_the_end: 0

chunk-price:
  default: 100000 # 개별 설정되지 않은 모든 월드 청크 가격
  each:
    survival: 50000 # 월드 별 청크 가격 설정

particle: end_rod